application: pledgecounter
version: auto
api_version: 1
runtime: python27
threadsafe: true

libraries:

- name: jinja2
  version: "2.6"

handlers:

- url: /_ah/admin/interactive.*
  script: google.appengine.ext.admin.application
  login: admin
  secure: always

- url: /_ah/spi/.*
  script: main.endpoints_application

- url: /public/csv
  script: main.application

- url: /public/(.*)
  static_files: public/\1
  upload: public/(.*)

#- url: /.*
#  script: main.application

skip_files:

- ^(.*/)?#.*#
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*\.so$
- ^(.*/)?.*\_test.(html|js|py)$
- ^(.*/)?.*~
- ^(.*/)?\..*
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
